### ISSUE TITLE
V2Ray 4.20下使用GPRC连接失败

### ISSUE THREAD

**Issue by JeskaiJet** [Ehco1996/v2scar#1]
使用示例配置文件启动V2Ray后无法启动v2scar 提示 “GRPC连接失败,请检查V2ray是否运行并开放对应grpc端口”
查询后发现inboundDetour已在4.0中弃用
v2scar是否暂不支持4.0版本的v2ray?

**Comment by Ehco1996** [comment]
不好意思才看到
这个问题一般是正在运行的v2ray的grpc端口没打开，或者没有被正确的转发

能把你的v2ray的config.json贴上来么
