### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Bluefissure** [Ehco1996/v2scar#2]
[README](https://github.com/Ehco1996/v2scar#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E) 中的
`./v2scar --api-endpoint="xxx" --grpc-endpoint="127.0.0.0:8080" --sync-time=60`
应该是
`./v2scar --api-endpoint="xxx" --grpc-endpoint="127.0.0.1:8080" --sync-time=60`

**Comment by Ehco1996** [comment]
fixed
