### ISSUE TITLE
请问作者怎么解决的代理问题？

### ISSUE THREAD

**Issue by neilbowman666** [Ehco1996/v2scar#5]
go小白：请问作者怎么解决的代理问题？
django-sspanel和这个新的v2scar好像文档都不太全的样子。
我在go build的时候直接给我整个网络错误出来。
配好七牛的go proxy了，v2ray的源又不能访问，proxychains4也不行。

**Comment by Ehco1996** [comment]
去v2ray/v2ray-core 的issues 里翻一下
